version: '2'
services:
  web:
    container_name: teste-pratico-node.web
    image: teste-pratico-node
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      TZ: America/Sao_Paulo
      PORT: '5000'
      HOST: '0.0.0.0'
      NODE_ENV: 'development'
      APP_KEY: 'OPzTu5i_G-BsIq7YqXUI9YYKMj-5grMm'
      DATABASE_URL: 'postgres://postgres:6cf37a1083ad1ef033a05e9c0b27e136@teste-pratico-node.postgres/TestePraticoNode'

  postgres:
    container_name: teste-pratico-node.postgres
    image: postgres:13-alpine
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6cf37a1083ad1ef033a05e9c0b27e136
      POSTGRES_DB: TestePraticoNode
    
